raw_data_config: 
  raw_data_csv: C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/data/raw/WildBlueberryPollinationSimulationData.csv
  model_var: ['clonesize','honeybee','bumbles','andrena','osmia','MaxOfUpperTRange','MinOfUpperTRange','AverageOfUpperTRange','MaxOfLowerTRange','MinOfLowerTRange','AverageOfLowerTRange','RainingDays','AverageRainingDays','fruitset','fruitmass','seeds','yield']
  train_test_split_ratio: 0.2
  target: yield 
  random_state: 123
  new_train_data_csv: C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/data/raw/train_new.csv

processed_data_config:
  train_data_csv: C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/data/processed/wb_train.csv
  test_data_csv:  C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/data/processed/wb_test.csv

mlflow_config:
  artifacts_dir: artifacts
  experiment_name: experiment-1
  run_name: xgboost-2
  registered_model_name: xgboost_model_1
  remote_server_uri: http://192.168.0.1:5000
 
xgboost: 
  max_depth: 7
  n_estimators: 30

model_dir: C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/models/model.joblib

model_webapp_dir: C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/webapp/model_webapp_dir/model.joblib

model_monitor:
  target_col_name: target
  monitor_dashboard_html: C:/Users/Chirag/Desktop/Wild-Blueberry-MLOps/reports/data_and_target_drift_dashboard.html